### ISSUE TITLE
Provide a way to toggle 'hits pr. page'

### ISSUE THREAD

**Issue by jorntx** [netarchivesuite/shine#10]
Provide a way to toggle 'hits pr. page'. 

Max pr. page should take performance into account.

**Comment by tokee** [comment]
Backend-wise (aka SolrCloud), there is very little difference between returning the documents for the first 10 or 50 hits. The bulk of the work is dictated by the total hit count.

**Comment by jorntx** [comment]
Good to know for future reference.

In this iteration we have decided not to implement this feature.
