### ISSUE TITLE
Page is not cleared on new search

### ISSUE THREAD

**Issue by thomasegense** [netarchivesuite/shine#16]
If you navigate to page 6 etc. and make a new search, the new search result will still start showing results from page 6.

**Comment by skovmand** [comment]
Jeg kan godt se problemet og checker det lige ud.

**Comment by skovmand** [comment]
Hvis jeg fjerner `<input type="hidden" name="page" value="@(currentPage.getCurrentPage)" />` fra `facets.scala.html` linje 42, forsvinder fejlen. Dog ved jeg ikke om jeg smadrer noget andet?

**Comment by skovmand** [comment]
Ja okay, det er selvfølgelig fordi den skal fastholde den nuværende side når man tilføjer/fjerner facetter.

**Comment by skovmand** [comment]
Okay. Det er fordi både facetter og søgefeltet deler den samme `<form>`

**Comment by skovmand** [comment]
The fix for this is to separate the facet form from the search form.

**Comment by skovmand** [comment]
This is the pull request to fix the issue:

**Comment by skovmand** [comment]
I made a mistake in the PR which was fixed in PR #23

**Comment by skovmand** [comment]
I have reopened the issue and reverted the changes I have made to the forms, because they have broken functionality in another areas.
