### ISSUE TITLE
Ability to disable search for anonymous users

### ISSUE THREAD

**Issue by skovmand** [netarchivesuite/shine#18]
Add the possibility to disable search for anonymous users. When using Shine in Denmark only authenticated users can search.

This should be implemented as a configuration option, so it can be changed easily without manipulating code.

**Comment by skovmand** [comment]
I've been working on an elegang solution using ActionBuilders in the branch `add-authorization-required-option`. However the work has stopped because I can't get access the Shine Configuration from inside the Action Filter. There must be a way though.

An alternative would be to implement the check in every controller necessary, but that seems like the wrong path and it would have a lot of duplication.

So for now I will leave this unresolved since it is not important.

**Comment by jorntx** [comment]
We have decided not to implement this feature and enforce security through Citrix/Apache instead.
