### ISSUE TITLE
Can't change search query for existing search 

### ISSUE THREAD

**Issue by skovmand** [netarchivesuite/shine#24]
When searching for any term from the search page, when searching for anything else, the search will be for the first term again. 

Reproduce:
1. Search for "cykel"
2. On the results page search for "fidus" instead and click Submit or Enter.
3. See that the query is still "cykel"

**Comment by thomasegense** [comment]
Jeg har lige testet mod BL gamle shine ( https://www.webarchive.org.uk/shine ) og der er fejlen ikke.
Men jeg kan reproducere dem som du beskriver og søgning er faktisk ubrugelig da man kun man lave en søgning og så efterfølgende skal slette i url så man genåbner forsiden af shine for at kunne søge igen.

**Comment by thomasegense** [comment]
Jeg har lige testet mod BL gamle shine ( https://www.webarchive.org.uk/shine ) og der er fejlen ikke.
Men jeg kan reproducere dem som du beskriver og søgning er faktisk ubrugelig da man kun man lave en søgning og så efterfølgende skal slette i url så man genåbner forsiden af shine for at kunne søge igen.

**Comment by thomasegense** [comment]
Årsag er at query params i URL ikke slettes, så der står query=xxx    & query = yyy. Den første vinder.
