### ISSUE TITLE
Add 'View full record' feature

### ISSUE THREAD

**Issue by jorntx** [netarchivesuite/shine#3]
Each search result should have way to view the full record. The full record view should list all the record's fields and preferably provide links on every field for further search.

**Comment by thomasegense** [comment]
Done. På branch fullrecord

**Comment by thomasegense** [comment]
Aahh. Der mangler stadig link til videre søgning...

**Comment by thomasegense** [comment]
Og reopen

**Comment by thomasegense** [comment]
DONE! Merge and delete branch plz.
