### ISSUE TITLE
Trend lines are inefficient

### ISSUE THREAD

**Issue by tokee** [netarchivesuite/shine#30]
Trend lines uses range faceting on `crawl_date` with `year` granularity. This is a technically sound, but fairly heavy process.

As the field `crawl_year` exists, an alternative is to do plain faceting facet on that with `rows=0&facet=true&facet.field=crawl_year&facet.sort=alpha`, which is a lot lighter (aka faster) for Solr to process.

**Comment by skovmand** [comment]
We will wait with fixing trendlines until the next version.
