### ISSUE TITLE
Facet exclusion not working

### ISSUE THREAD

**Issue by tokee** [netarchivesuite/shine#33]
Reproduce by issuing a search, switch to exclude mode for `Domain` and click one of the domains in the facet. The page refreshed and shows that the domain is excluded, but it is still present in the facet.

**Comment by skovmand** [comment]
@thomasegense Your help is needed here.

**Comment by thomasegense** [comment]
Lukket issue. Opret ny issue som kun er GUI issue

**Comment by thomasegense** [comment]
Funktionsmæssigt fungerer det, og den virker som Shine/BL
