### ISSUE TITLE
Harvest year visualization

### ISSUE THREAD

**Issue by tokee** [netarchivesuite/shine#34]
Niels Brügger suggests a search result aggregation where the results are grouped by `domain` and visualized by a graph showing harvest dates for all the material in each domain.

This is not feasible in version 2 of Netarchive Search, but quite easy with Solr 6 (Netarchive Search version 3) using nested faceting. A poor man's version is to do grouping on `domain` with `fl=crawl_year&group.limit=100`, which will return the 100 harvest-years for each domain, giving a (poor with large result sets) approximation.

**Comment by skovmand** [comment]
It's a good idea. We will look at it in the next version.
