### ISSUE TITLE
Export to CSV is broken

### ISSUE THREAD

**Issue by jorntx** [netarchivesuite/shine#5]
Two problems (interlinked) with export to CSV that need to be handled:
1. Export to CSV function is broken
2. Export to CSV breaks when exporting large search result sets

**Comment by thomasegense** [comment]
Problem 1) is fixed.
Problem 2) will be too hard to fix for now and was also not working in the old shine.

**Comment by thomasegense** [comment]
Fixed and merged into develop branch 
PR: #22
