### ISSUE TITLE
Relevance sorting (sort by score) is not default

### ISSUE THREAD

**Issue by jorntx** [netarchivesuite/shine#6]
Search results should be sorted after relevance as default.

**Comment by thomasegense** [comment]
If you select the "score" option under advanced search, it will 
sort by "sort=sentiment_score" and not "sort=score" 
The sentiment_score is a field that is never used.

**Comment by michaelpoltorak** [comment]
So all occurrences of sentiment_score need to be replaced by score?

**Comment by thomasegense** [comment]
Correct. I doubt British Library want to sort on sentiment_score. If needed there must be both options.

**Comment by michaelpoltorak** [comment]
I've set score as default option and included sentiment_score in the option list

**Comment by michaelpoltorak** [comment]
@skovmand On the SHINE-7-more-sort-options branch I've set score as default sort option in the conf/routes file. This seems to solve this issue too ;-)

**Comment by skovmand** [comment]
Nice!

**Comment by skovmand** [comment]
Er den klar til at blive merged?

**Comment by michaelpoltorak** [comment]
yes

**Comment by skovmand** [comment]
Fixed in #21
