### ISSUE TITLE
Provide more sorting options to search result

### ISSUE THREAD

**Issue by jorntx** [netarchivesuite/shine#7]
The user should be able to choose to sort search results by:
- relevance/score (default)
- crawl data (asc/dec
- url (a-z)
- url (z-a)
- content type (a-z)
- content type (z-a)

**Comment by michaelpoltorak** [comment]
Now resolved on branch SHINE-7-more-sort-options. 
The sort and order selectors have been merged to one including all options.
Sort by title is still included besides the above options, but is unclear if it is needed.
